### ISSUE TITLE
Issue new release

### ISSUE THREAD

**Issue by Mossop** [Mossop/bugzilla-ts#15]
With the changes to support Red Hat it may be time to release a new version. The type changes I think would make this a major update (any dependent project using TypeScript could break) so the next release would be v2.0.0.

**Comment by jamacku** [comment]
@Mossop I'm looking forward to `v2.0.0`, when do you plan to make a release, can I help? Thank you! :+1:

**Comment by Mossop** [comment]
Sorry I got distracted with other work. I've just published v2.0.0 to npm.

**Comment by jamacku** [comment]
That's ok, thank you for your work on release!
