### ISSUE TITLE
Integration tests rely on live data

### ISSUE THREAD

**Issue by Mossop** [Mossop/bugzilla-ts#52]
The tests that pull bugs from live Mozilla and RedHat bugzillas rely on that data remaining constant. If someone changes their display name then the tests start to fail. We should probably just test the general shape of the returned data and not the specific values.

**Comment by jamacku** [comment]
Short term workaround could be to cherry-pick bugs that have a smaller number of "moving parts". Old bugs, bugs with small amounts of comments and CC, etc.

**Comment by Mossop** [comment]
I'm close to being able to resolve this with #91

**Comment by jamacku** [comment]
> I'm close to being able to resolve this with #91

Thanks for working on it!
